### ISSUE TITLE
[Bug] Incorrect handling of German umlauts

### ISSUE THREAD

**Issue by Mosrite** [nbenm/ImapNote2#10]
Hello,

apparently, the app has problems handling German umlauts such as ä, ö and ü.
It would be great if this could be fixed!

Thanks in advance!

**Comment by N0ury** [comment]
Hi Mosrite,

I have tried this today.
I've configured my keyboard as German then typed some characters.
I could type ö, ü and ë easily. I had just to push the letter o, then wait a popup to appear for selecting ö.
Same with other letters.
So I don't understand what your problem is. Can you please explain it more.

Regards

Noury

**Comment by Mosrite** [comment]
Hey, thanks for testing this! The problem occurs when I create notes in my iPhone or with the webapp of my email provider (posteo.de). If I use Umlauts there, they are not displayed correctly within the Android app, but instead other smybols (like %, &, / etc.) are used. Hope that helps!

**Comment by N0ury** [comment]
Hi Mosrite,

I have created a posteo.de account and configured my Android to use German.
I have then created a note containing ü ä ë via the webapp.
On the the phone, titles are displayed incorrectly, but notes content is ok.
Can you confirm this, or is it different for you ?

Regards

Noury

**Comment by Mosrite** [comment]
Hi, I just tested it and the results were the following:

Note created with an iPhone: No problems handling Umlauts.
Note created within the Posteo webapp: Umlauts are replaced by symbols in the note title overview. Umlauts are displayed correctly when the note is opened (both title and content).

**Comment by N0ury** [comment]
Hi Mosrite,

The problem is that posteo.de does not respect the encoding rules of the subjects.
RFC 2047 provides that us non ascii characters in the subjects are encoded. Posteo.de do not.
So I had to work around the issue.
Here is a program to solve the problem. Can you please test it and tell me if it's ok (rename imapnote2.zip imapnote2.apk first)

[imapnote2.zip](https://github.com/nbenm/ImapNote2/files/75941/imapnote2.zip)

Regarde

Noury

**Comment by Mosrite** [comment]
Hello Noury, that worked, thanks a lot!

**Comment by N0ury** [comment]
Release 4.8 has been submitted to Google Play
